### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by bam241** [bam241/weather_study#2]
- [ ] make a container for weather data
- [ ] store weather data
- [ ] set a reader for weather data
  - [ ] for dark sky/forcast.io
  - [ ] weather underground / weather channel
  - [ ] NWS
  - [ ] NOAA
